#!/usr/bin/python

import glob

def reformat_line(s):
    out = []
    brace_stack = []
    flip_braces = {'}': '{', ']': '[', ')': '(', '>': '<'}
    for c in s:
        out.append(c)
        if c in '{[(<':
            brace_stack.append(c)
        elif c in flip_braces:
            assert brace_stack.pop() == flip_braces[c]

        if c == '{' and brace_stack == ['{']:
            out.append("\n ")
        if c == ',' and brace_stack == ['{']:
            out.append("\n ")
    return "".join(out)

lines = [
    "// Generated by concat_types.py, from the output of https://github.com/Aleph-Alpha/ts-rs\n",
    "// Run `cargo test` then `python concat_types.py` to rebuild.\n",
    "\n",
]
for filename in glob.glob("bindings/*.ts"):
    with open(filename, "r") as f:
        for line in f:
            if line.startswith("export"):
                lines.append(reformat_line(line) + "\n\n")

s = "".join(lines)
s = s.replace("bigint", "number")
s = s.replace('"', "'")
s = s.replace("  }", "}")

print(s)

with open("../src/RustTypes.ts", "w") as f:
    f.write(s)

